# Generated by Django 3.2.18 on 2023-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterField(
            model_name='receta',
            name='RENTABILIDAD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
