# Generated by Django 3.2.18 on 2023-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_auto_20230506_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='PRODUCTO',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
