# Generated by Django 3.2.18 on 2023-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='deuda_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='deuda actual'),
        ),
    ]
